name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4
    - name: Visual Studio shell
      uses: egor-tensin/vs-shell@v2
    - name: make
      run: CI
